### ISSUE TITLE
Dazel + Python2

### ISSUE THREAD

**Issue by TimZaman** [nadirizr/dazel#28]
Hello! Thanks for a neat tool. Currently giving it a spin on OS-X with Python2.7.
So `dazel.py` seems to depend on Python 3 per `#!/usr/bin/env python3` and usage of some Python3 functionality i.e.`shutil.get_terminal_size()`. Is dazel supposed to work with python 2 at all? If no, should it be py2 compatible on [Pypi](https://pypi.python.org/pypi/dazel)?

**Comment by mishas** [comment]
Hello Tim,

First of all, let me say that dazel is a binary, so you shouldn't care if it's python3 or python2. If you want to use it - just install python3 alongside with python2 on your mac, and use dazel.

With that said, you're right about the shutil: We should either not use it, or define dazel as non-python2 compatible. I'm leaving this ticket open so that we'll do that at some point.

BTW - The shebang line is actually irrelevant. Due to how it's defined in the setup.py file, there's actually another entrypoint created (with a different shebang line), that imports this file. So - as long as we didn't use shutil, it would've worked with python2 even with that "bad" shebang line.

**Comment by llarco** [comment]
Hi,

I'm running into this issue with `shutil.get_terminal_size()`:

```
$ dazel build //...:all
Traceback (most recent call last):
  File "/usr/local/bin/dazel", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/dazel.py", line 541, in main
    return di.send_command(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/dazel.py", line 140, in send_command
    term_size = shutil.get_terminal_size()
AttributeError: 'module' object has no attribute 'get_terminal_size'
```

I do have both versions of python installed. Is there any specific configuration I should use? Otherwise, is there a workaround to the `shutil.get_terminal_size()` line?

**Comment by mishas** [comment]
Uninstall dazel (`pip uninstall dazel`) and install it again with pip3 (`pip3 install dazel`).
Should work then. You might need to start a new shell window for that.

**Comment by llarco** [comment]
> Uninstall dazel (`pip uninstall dazel`) and install it again with pip3 (`pip3 install dazel`).
> Should work then. You might need to start a new shell window for that.

That worked, thanks!
